### ISSUE TITLE
Use RC API to skip matches on first day of batches 

### ISSUE THREAD

**Issue by jaryncolbert** [thechutrain/rc-coffee-chats#50]
@thechutrain mentioned that one of the roles of a maintainer was to skip all matches on the first day of a batch because there's already so much packed into that first day. 

I suggested looking into automating this with data from the [RC API](https://github.com/recursecenter/wiki/wiki/Recurse-Center-API), which has info about the start and end dates of each batch. 

The [Batches](https://github.com/recursecenter/wiki/wiki/Recurse-Center-API#batches) endpoint ([data](https://www.recurse.com/api/v1/batches/)) would be perfect for this, as it returns just the data you need - batch id, start date, end date, and display name. One caveat: right now, it only returns batches that have started, so I'm not sure if this will work for getting data about the next batch. 

But the [Profiles](https://github.com/recursecenter/wiki/wiki/Recurse-Center-API#profiles) endpoint, which returns all data about each member of the RC community, also has info about batches; the downside here is that it would require processing more data to get the info you need.  

I'm going to log an issue in the RC Issue Tracker to update `/batches` to return future batch info, and I'll link it here for traceability.

**Comment by thechutrain** [comment]
@jaryncolbert Thanks so much, this is a great suggestion! Any feature that would help automate transitions should probably be prioritized as they would lower the barrier of responsibilities for the maintainer and keep the bot going smoothly.

Looking at the RC API briefly, it seems that we could determine whether a new batch has begun or not by querying the `/api/v1/batches` and comparing that to a stored value (configs table) of the most recent batch. Perhaps that would be sufficient in determining that any given day is the first day of the batch. One thing to consider though is when the new `/batches` gets updated in the RC database. I assume as long as it's before the first day we should be all set, since the API provides data on the start date and we can add that to our exception_dates table.

Also, if we have the `batch_id` of the new batch, it looks like we can query for the all the new RCers by passing a query string to the `/api/v1/profiles` endpoint to get all the new RCers who we can message directly about signing up for chat bot.

**Comment by thechutrain** [comment]
Closing this issue since this feature since it is no longer a priority to not have matches on the first day of the batch. By default, users are warned the previous day that they will be matched.

Using the RC api was very useful for automating the on- and off-boarding of chat bot users.
